appName: dropwizard-kotlin-example

server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      certAlias: dropwizard-kotlin-example
      keyStorePath: keystore.pfx
      keyStorePassword: changeit
      validateCerts: false
      supportedProtocols: [TLSv1.2]
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: logs/dropwizard-kotlin-example
      archivedLogFilenamePattern: logs/dropwizard-kotlin-example-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC